### ISSUE TITLE
Make animation of a 48-hour period

### ISSUE THREAD

**Issue by ehmatthes** [ehmatthes/sitka_irg_realtime#2]
This is the main issue for making an animation of 48-hour periods of rainfall. Will want to make several animations focusing on periods where a landslide occurred, and periods that came close to being critical but where no slide occurred.

**Comment by ehmatthes** [comment]
## Tasks

- [ ] Identify a set of readings to focus on.
- [ ] Adapt existing plotting code to generate animation.

**Comment by ehmatthes** [comment]
- [ ] adjust so it's an actual 48-hour period
  - [ ] should adjust source file, so can rerun animation plotting code
  - for 48 hour period at 15-min intervals, need 48 hours before and 48 hours after initial lead point (far right point on plot)
    - this is 48*4 + 48*4 = 384
    - for hourly readings, this is simply 48*2 = 96

**Comment by ehmatthes** [comment]
- [ ] Generate animation for Kramer slide event.
  - [ ] Grab readings, probably from irg_analysis work.

**Comment by ehmatthes** [comment]
- [ ] Choose other significant periods to animate.

**Comment by ehmatthes** [comment]
## Refinements

- [ ] For historical animations, may want to plot critical region for as much of the period shown as possible, ie ~40 hours rather than just last 6.

**Comment by ehmatthes** [comment]
Moving this work to sitka_irg_analysis.

**Comment by mansoor96g** [comment]
hi. i'm very interested in your project. how can i help

**Comment by ehmatthes** [comment]
Hi @mansoor96g. What interests you about this project?

**Comment by mansoor96g** [comment]
i want to contribute to this project to enhances my datascience and machine learning skills. 

i recently finished coursera [applied data science](https://www.coursera.org/specializations/data-science-python) specialization. and this project uses matplotlib (my favorite) with a real data in a web app. pules it has the right size and complexity for me to be  challenging enough but not overwhelmed.

what i could do: 

- i could build more interactive visualizations ( although i'm not sure how that is done in a web environment) . 

- i can apply data analysis and put more emphasis on the massage intended or provide a supplement summary charts .

- provide a dashboard to interact with the charts.

although i'm not a developer per say. i hope that it's possible to apply my skills sit and learn at the same time. 

and thanks for you response

**Comment by ehmatthes** [comment]
Hi again @mansoor96g. Thanks for clarifying. This web-focused project isn't really ready for collaboration yet. If you are intested in this projec, [this](https://github.com/ehmatthes/sitka_irg_analysis) is a better one to contribute to. That project is an analysis of historical data that justifies this project. That project is in a pretty messy state because I just finished the exploratory phase of the project. I'm going to clean up that project over the next few weeks, and write up the process. If you want to get involved, feel free to open a "how can I help" issue on that project, and I'll fill you in more there.

There has been some suggestion to apply ML techniques to that dataset, and if you're interested I'd be happy to see any results you obtain in that direction. I'm not sure if it's a large enough dataset to benefit from ML techniques, but I don't know much at all about practical ML application yet.

**Comment by mansoor96g** [comment]
thanks.

i will defiantly follow your advice check that out.
