### ISSUE TITLE
Resuming work on this project

### ISSUE THREAD

**Issue by ehmatthes** [ehmatthes/sitka_irg_realtime#4]
I haven't touched this project in 5 months. I am happy to see that it has been running uninterrupted since then.

The [devastation in Haines yesterday](https://www.adn.com/alaska-news/weather/2020/12/02/record-rainfall-prompts-flooding-avalanches-and-landslides-in-southeast-alaska/) (12/2/20) raises the urgency on this work. What happened in Haines could have easily happened here, and I don't sleep well sitting on this work anymore.

This issue is just for resuming the work on a stale project; another issue will focus on the specific work that needs to be done.

## Tasks

- [x] Run the project locally.
- [x] Log in to the server and look at its current usage/ memory/ etc.
  - Not worth getting into detail at this point other than nothing obvious to worry about.
- [x] Write up a series of issues to start with, including appropriate labels.
- [x] Update documentation.

**Comment by ehmatthes** [comment]
- [ ] Update documentation
  - [ ] Start a my_docs directory, and start with running_locally.
  - [ ] Install macdown, and use that to develop documentation locally.
  - [ ] Add a readme. Describe the project, and how to run it locally.
